services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
    volumes:
      - mongo-data:/data/db

  todo:
    container_name: todo-ops
    build:
      context: ./
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - MONGODB_URI=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASS}@mongo:27017/todoops?authSource=admin
    depends_on:
      - mongo

volumes:
  mongo-data:
