services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
      MONGO_APP_USER: ${MONGO_APP_USER}
      MONGO_APP_PASS: ${MONGO_APP_PASS}
    volumes:
      - mongo-data:/data/db
      - ./init.js:/docker-entrypoint-initdb/init.js.d:ro
    healthcheck:
      test: mongosh --eval "db.runCommand('ping')"
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  todo:
    container_name: todo-ops
    build:
      context: ./
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - MONGODB_URI=mongodb://${MONGO_APP_USER}:${MONGO_APP_PASS}@mongo:27017/todoops?authSource=todoops
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo-data:
